// Copyright 2026 Kisaes LLC
// Licensed under the PolyForm Internal Use License 1.0.0.
// You may not distribute this software. See LICENSE for terms.

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { canonicalize } from '../utils/canonical-json.js';
import { crc32 } from '../utils/crc32.js';
import { writeAtomicSync } from '../utils/atomic-write.js';

/**
 * Installation sentinel file — a tamper-evident record that proves this
 * storage volume was once associated with a completed setup. Used by
 * installation-validator.ts to detect scenarios where the Postgres volume
 * has been wiped (or a wrong DATABASE_URL is pointed at an empty DB) while
 * the `/data` bind mount still holds files from the real installation.
 *
 * File format ("KISS" — KIS Books Sentinel):
 *
 *   offset  len  field
 *   ------  ---  -----
 *   0       4    magic "KISS"
 *   4       1    format version (currently 1)
 *   5       2    header length N (big-endian uint16)
 *   7       N    header JSON (canonical, readable WITHOUT the key)
 *   7+N     4    CRC32 of the N header bytes (big-endian)
 *   11+N    12   GCM IV
 *   23+N    16   GCM auth tag
 *   39+N    M    GCM ciphertext of the canonical-JSON payload
 *
 * The unencrypted header is why this can't reuse `portable-encryption.service.ts`:
 * the validator must be able to display installation ID and setup date on a
 * diagnostic page even when the ENCRYPTION_KEY is wrong or missing.
 *
 * CRC32 covers the header bytes so corruption can be distinguished from a
 * wrong-key failure — GCM auth tag failures are indistinguishable from
 * random-byte flips without it.
 *
 * See SETUP_SENTINEL_PLAN.md and plans/serialized-watching-moler.md F3/F4/F16.
 */

const MAGIC = Buffer.from('KISS', 'ascii');
const FORMAT_VERSION = 1;
const IV_LENGTH = 12;
const TAG_LENGTH = 16;
const CIPHER = 'aes-256-gcm';

/**
 * Resolved lazily so tests can override DATA_DIR at runtime. Production reads
 * the env var once at startup, so the per-call cost is trivial.
 */
export function getSentinelPath(): string {
  return path.join(process.env['DATA_DIR'] || '/data', '.sentinel');
}

/** Fields readable from the sentinel file without the encryption key. */
export interface SentinelHeader {
  v: 1;
  installationId: string;
  hostId: string;
  createdAt: string;
  adminEmail: string;
  appVersion: string;
}

/** Fields that exist only in the encrypted payload. */
export interface SentinelPayloadExtras {
  databaseUrlHash: string;
  jwtSecretHash: string;
  tenantCountAtSetup: number;
}

/** Full decrypted payload. Contains everything in the header plus extras. */
export interface SentinelPayload extends SentinelHeader, SentinelPayloadExtras {
  checksum: string;
}

/** Input to createSentinel — the caller supplies these; the service derives the rest. */
export interface CreateSentinelInput {
  installationId: string;
  hostId: string;
  adminEmail: string;
  appVersion: string;
  databaseUrl: string;
  jwtSecret: string;
  tenantCountAtSetup: number;
  createdAt?: Date;
}

/** Errors thrown by this service. */
export class SentinelError extends Error {
  constructor(
    message: string,
    public readonly code:
      | 'MAGIC_MISMATCH'
      | 'VERSION_UNSUPPORTED'
      | 'TRUNCATED'
      | 'HEADER_CRC_FAILED'
      | 'DECRYPT_FAILED'
      | 'CHECKSUM_FAILED'
      | 'WRITE_FAILED',
  ) {
    super(message);
    this.name = 'SentinelError';
  }
}

function deriveKey(encryptionKey: string): Buffer {
  // Accept either a 64-char hex string (preferred — generated by setup) or an
  // arbitrary passphrase that we SHA-256 down to 32 bytes. Matches the
  // convention used by utils/encryption.ts for PLAID_ENCRYPTION_KEY.
  if (encryptionKey.length === 64 && /^[0-9a-f]+$/i.test(encryptionKey)) {
    return Buffer.from(encryptionKey, 'hex');
  }
  return crypto.createHash('sha256').update(encryptionKey).digest();
}

function computeChecksum(payloadWithoutChecksum: Omit<SentinelPayload, 'checksum'>): string {
  return crypto
    .createHash('sha256')
    .update(canonicalize(payloadWithoutChecksum))
    .digest('hex');
}

function encodeFile(header: SentinelHeader, payload: SentinelPayload, key: Buffer): Buffer {
  const headerBytes = Buffer.from(canonicalize(header), 'utf8');
  if (headerBytes.length > 0xffff) {
    throw new SentinelError('sentinel header too large', 'WRITE_FAILED');
  }
  const headerCrc = crc32(headerBytes);

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(CIPHER, key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(canonicalize(payload), 'utf8'),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();

  const out = Buffer.alloc(4 + 1 + 2 + headerBytes.length + 4 + IV_LENGTH + TAG_LENGTH + ciphertext.length);
  let off = 0;
  MAGIC.copy(out, off);
  off += 4;
  out.writeUInt8(FORMAT_VERSION, off);
  off += 1;
  out.writeUInt16BE(headerBytes.length, off);
  off += 2;
  headerBytes.copy(out, off);
  off += headerBytes.length;
  out.writeUInt32BE(headerCrc, off);
  off += 4;
  iv.copy(out, off);
  off += IV_LENGTH;
  authTag.copy(out, off);
  off += TAG_LENGTH;
  ciphertext.copy(out, off);
  return out;
}

interface ParsedFile {
  header: SentinelHeader;
  headerBytes: Buffer;
  iv: Buffer;
  authTag: Buffer;
  ciphertext: Buffer;
}

function parseFile(buf: Buffer): ParsedFile {
  if (buf.length < 4 + 1 + 2 + 4 + IV_LENGTH + TAG_LENGTH) {
    throw new SentinelError('sentinel file truncated', 'TRUNCATED');
  }
  if (!buf.subarray(0, 4).equals(MAGIC)) {
    throw new SentinelError('sentinel magic bytes do not match', 'MAGIC_MISMATCH');
  }
  const version = buf.readUInt8(4);
  if (version !== FORMAT_VERSION) {
    throw new SentinelError(`unsupported sentinel format version ${version}`, 'VERSION_UNSUPPORTED');
  }
  const headerLen = buf.readUInt16BE(5);
  const headerStart = 7;
  const headerEnd = headerStart + headerLen;
  if (buf.length < headerEnd + 4 + IV_LENGTH + TAG_LENGTH) {
    throw new SentinelError('sentinel file truncated at header', 'TRUNCATED');
  }
  const headerBytes = buf.subarray(headerStart, headerEnd);
  const expectedCrc = buf.readUInt32BE(headerEnd);
  const actualCrc = crc32(headerBytes);
  if (expectedCrc !== actualCrc) {
    throw new SentinelError('sentinel header CRC mismatch (file is corrupt)', 'HEADER_CRC_FAILED');
  }

  let header: SentinelHeader;
  try {
    header = JSON.parse(headerBytes.toString('utf8')) as SentinelHeader;
  } catch {
    throw new SentinelError('sentinel header is not valid JSON', 'HEADER_CRC_FAILED');
  }
  if (!header || typeof header !== 'object' || header.v !== 1) {
    throw new SentinelError('sentinel header missing required fields', 'HEADER_CRC_FAILED');
  }

  const ivStart = headerEnd + 4;
  const tagStart = ivStart + IV_LENGTH;
  const cipherStart = tagStart + TAG_LENGTH;
  const iv = buf.subarray(ivStart, ivStart + IV_LENGTH);
  const authTag = buf.subarray(tagStart, tagStart + TAG_LENGTH);
  const ciphertext = buf.subarray(cipherStart);

  return { header, headerBytes, iv, authTag, ciphertext };
}

/** Create and atomically write a sentinel file. Throws on any failure. */
export function createSentinel(input: CreateSentinelInput, encryptionKey: string): void {
  const header: SentinelHeader = {
    v: 1,
    installationId: input.installationId,
    hostId: input.hostId,
    createdAt: (input.createdAt ?? new Date()).toISOString(),
    adminEmail: input.adminEmail,
    appVersion: input.appVersion,
  };

  const payloadBase: Omit<SentinelPayload, 'checksum'> = {
    ...header,
    databaseUrlHash: crypto.createHash('sha256').update(input.databaseUrl).digest('hex'),
    jwtSecretHash: crypto.createHash('sha256').update(input.jwtSecret).digest('hex'),
    tenantCountAtSetup: input.tenantCountAtSetup,
  };
  const payload: SentinelPayload = { ...payloadBase, checksum: computeChecksum(payloadBase) };

  const key = deriveKey(encryptionKey);
  const encoded = encodeFile(header, payload, key);

  try {
    writeAtomicSync(getSentinelPath(), encoded, 0o600);
  } catch (err) {
    throw new SentinelError(
      `failed to write sentinel file at ${getSentinelPath()}: ${(err as Error).message}`,
      'WRITE_FAILED',
    );
  }
}

/** Does a sentinel file exist at the expected path? */
export function sentinelExists(): boolean {
  return fs.existsSync(getSentinelPath());
}

/**
 * Read and validate the unencrypted header. Returns null if the file does not
 * exist; throws SentinelError on any parse/CRC failure. Does NOT require
 * ENCRYPTION_KEY — safe to call during pre-env bootstrap.
 */
export function readSentinelHeader(): SentinelHeader | null {
  if (!sentinelExists()) return null;
  const buf = fs.readFileSync(getSentinelPath());
  const parsed = parseFile(buf);
  return parsed.header;
}

/**
 * Read, decrypt, and validate the full sentinel payload. Returns null if the
 * file does not exist. Throws SentinelError with distinct codes for corrupt
 * header (HEADER_CRC_FAILED) vs wrong key / tampered ciphertext (DECRYPT_FAILED)
 * vs payload integrity failure (CHECKSUM_FAILED).
 */
export function readSentinelPayload(encryptionKey: string): SentinelPayload | null {
  if (!sentinelExists()) return null;
  const buf = fs.readFileSync(getSentinelPath());
  const parsed = parseFile(buf);

  const key = deriveKey(encryptionKey);
  const decipher = crypto.createDecipheriv(CIPHER, key, parsed.iv);
  decipher.setAuthTag(parsed.authTag);
  let plain: string;
  try {
    plain = Buffer.concat([decipher.update(parsed.ciphertext), decipher.final()]).toString('utf8');
  } catch {
    throw new SentinelError(
      'sentinel ciphertext failed GCM authentication — wrong ENCRYPTION_KEY or tampering',
      'DECRYPT_FAILED',
    );
  }

  let payload: SentinelPayload;
  try {
    payload = JSON.parse(plain) as SentinelPayload;
  } catch {
    throw new SentinelError('sentinel payload is not valid JSON', 'DECRYPT_FAILED');
  }

  const { checksum, ...payloadBase } = payload;
  const expected = computeChecksum(payloadBase);
  if (checksum !== expected) {
    throw new SentinelError('sentinel payload checksum mismatch', 'CHECKSUM_FAILED');
  }

  // The encrypted payload must agree with the plaintext header on installation
  // ID and host ID. If it doesn't, someone has tampered with the header bytes
  // and the CRC wasn't enough to catch it — we catch it here.
  if (payload.installationId !== parsed.header.installationId || payload.hostId !== parsed.header.hostId) {
    throw new SentinelError(
      'sentinel header and payload disagree on installation or host ID',
      'CHECKSUM_FAILED',
    );
  }

  return payload;
}

/** Delete the sentinel file. Used by reset-sentinel CLI and intentional resets. */
export function deleteSentinel(): void {
  if (sentinelExists()) fs.unlinkSync(getSentinelPath());
}
