// Copyright 2026 Kisaes LLC
// Licensed under the PolyForm Small Business License 1.0.0.
// Free for small businesses; see LICENSE for terms.

import { useEffect, useState, type FormEvent } from 'react';
import { CheckCircle, Loader2, RotateCcw } from 'lucide-react';
import {
  DEFAULT_PL_LABELS,
  DEFAULT_BS_LABELS,
  DEFAULT_CF_LABELS,
  REPORT_FOOTER_MAX_LENGTH,
  type PLSectionLabels,
  type BSSectionLabels,
  type CFSectionLabels,
} from '@kis-books/shared';
import { apiClient } from '../../api/client';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';

type PLField = keyof PLSectionLabels;
type BSField = keyof BSSectionLabels;
type CFField = keyof CFSectionLabels;

const PL_ORDER: Array<{ key: PLField; helper: string }> = [
  { key: 'revenue', helper: 'Top-line sales/income section' },
  { key: 'cogs', helper: 'Direct costs of producing revenue (only shown when COGS accounts exist)' },
  { key: 'grossProfit', helper: 'Subtotal: Revenue − COGS' },
  { key: 'expenses', helper: 'Operating expenses section' },
  { key: 'operatingIncome', helper: 'Subtotal: Gross Profit − Operating Expenses' },
  { key: 'otherRevenue', helper: 'Non-operating income (interest earned, gains) — only shown when such accounts exist' },
  { key: 'otherExpenses', helper: 'Non-operating expense (interest paid, losses) — only shown when such accounts exist' },
  { key: 'netIncome', helper: 'Final bottom-line total' },
];

const BS_ORDER: Array<{ key: BSField; helper: string }> = [
  { key: 'assets', helper: 'What the business owns' },
  { key: 'liabilities', helper: 'What the business owes' },
  { key: 'equity', helper: 'Owner’s residual interest (Assets − Liabilities)' },
  { key: 'totalLiabilitiesAndEquity', helper: 'Closing total at the bottom of the report (must equal Total Assets)' },
];

const CF_ORDER: Array<{ key: CFField; helper: string }> = [
  { key: 'operatingActivities', helper: 'Cash generated by core business operations' },
  { key: 'investingActivities', helper: 'Cash spent on or received from capital investments' },
  { key: 'financingActivities', helper: 'Cash from loans, owner contributions, dividends' },
  { key: 'netChange', helper: 'Bottom-line change in cash for the period' },
];

interface ApiResponse {
  plLabels: Partial<PLSectionLabels>;
  bsLabels: Partial<BSSectionLabels>;
  cfLabels: Partial<CFSectionLabels>;
  reportFooter: string;
  firmName?: string;
  firmCity?: string;
  firmState?: string;
  accountantSignature?: string;
  resolvedPLLabels: PLSectionLabels;
  resolvedBSLabels: BSSectionLabels;
  resolvedCFLabels: CFSectionLabels;
}

export function ReportLabelsPage() {
  const [pl, setPL] = useState<PLSectionLabels>(DEFAULT_PL_LABELS);
  const [bs, setBS] = useState<BSSectionLabels>(DEFAULT_BS_LABELS);
  const [cf, setCF] = useState<CFSectionLabels>(DEFAULT_CF_LABELS);
  const [footer, setFooter] = useState('');
  // CPA firm identity for SSARS-21 engagement-letter signature blocks.
  const [firm, setFirm] = useState({ firmName: '', firmCity: '', firmState: '', accountantSignature: '' });
  const [loading, setLoading] = useState(true);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [saveError, setSaveError] = useState('');

  useEffect(() => {
    (async () => {
      try {
        const data = await apiClient<ApiResponse>('/tenant-settings/report');
        // Guard against partial responses (e.g. test mocks omitting one of
        // the resolved-*Labels keys) — merge each group over defaults so
        // missing fields revert rather than blowing up the form.
        if (data?.resolvedPLLabels) setPL({ ...DEFAULT_PL_LABELS, ...data.resolvedPLLabels });
        if (data?.resolvedBSLabels) setBS({ ...DEFAULT_BS_LABELS, ...data.resolvedBSLabels });
        if (data?.resolvedCFLabels) setCF({ ...DEFAULT_CF_LABELS, ...data.resolvedCFLabels });
        if (typeof data?.reportFooter === 'string') setFooter(data.reportFooter);
        setFirm({
          firmName: data?.firmName ?? '',
          firmCity: data?.firmCity ?? '',
          firmState: data?.firmState ?? '',
          accountantSignature: data?.accountantSignature ?? '',
        });
      } catch {
        // defaults are fine
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const resetAll = () => {
    setPL(DEFAULT_PL_LABELS);
    setBS(DEFAULT_BS_LABELS);
    setCF(DEFAULT_CF_LABELS);
    setFooter('');
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setSaveStatus('saving');
    setSaveError('');
    try {
      // Only send fields that differ from defaults so clearing a field
      // in the UI reverts that heading instead of being stored as empty.
      const plLabels: Partial<PLSectionLabels> = {};
      for (const key of Object.keys(DEFAULT_PL_LABELS) as PLField[]) {
        const v = pl[key]?.trim() || '';
        if (v && v !== DEFAULT_PL_LABELS[key]) plLabels[key] = v;
      }
      const bsLabels: Partial<BSSectionLabels> = {};
      for (const key of Object.keys(DEFAULT_BS_LABELS) as BSField[]) {
        const v = bs[key]?.trim() || '';
        if (v && v !== DEFAULT_BS_LABELS[key]) bsLabels[key] = v;
      }
      const cfLabels: Partial<CFSectionLabels> = {};
      for (const key of Object.keys(DEFAULT_CF_LABELS) as CFField[]) {
        const v = cf[key]?.trim() || '';
        if (v && v !== DEFAULT_CF_LABELS[key]) cfLabels[key] = v;
      }
      await apiClient('/tenant-settings/report', {
        method: 'PUT',
        body: JSON.stringify({
          plLabels,
          bsLabels,
          cfLabels,
          reportFooter: footer.trim(),
          firmName: firm.firmName.trim(),
          firmCity: firm.firmCity.trim(),
          firmState: firm.firmState.trim(),
          accountantSignature: firm.accountantSignature.trim(),
        }),
      });
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    } catch (err) {
      setSaveStatus('error');
      setSaveError(err instanceof Error ? err.message : 'Failed to save');
    }
  };

  if (loading) {
    return <div className="flex items-center gap-2 text-gray-500"><Loader2 className="h-4 w-4 animate-spin" /> Loading…</div>;
  }

  return (
    <div className="max-w-2xl">
      <h1 className="text-2xl font-bold text-gray-900 mb-2">Report Headings</h1>
      <p className="text-sm text-gray-500 mb-6">
        Rename the section headings on your Profit &amp; Loss, Balance Sheet, and Cash Flow Statement,
        and add an optional footer that shows below each of the three reports (on screen, in CSV,
        and on PDF exports). Leave a heading blank or click <span className="inline-flex items-center gap-1"><RotateCcw className="h-3 w-3" />Reset</span>
        {' '}to restore its default.
      </p>

      <form onSubmit={handleSubmit} className="space-y-8">
        <LabelGroup
          title="Profit & Loss"
          fields={PL_ORDER}
          defaults={DEFAULT_PL_LABELS}
          values={pl}
          onChange={(k, v) => setPL((f) => ({ ...f, [k]: v }))}
          onReset={(k) => setPL((f) => ({ ...f, [k]: DEFAULT_PL_LABELS[k] }))}
        />
        <LabelGroup
          title="Balance Sheet"
          fields={BS_ORDER}
          defaults={DEFAULT_BS_LABELS}
          values={bs}
          onChange={(k, v) => setBS((f) => ({ ...f, [k]: v }))}
          onReset={(k) => setBS((f) => ({ ...f, [k]: DEFAULT_BS_LABELS[k] }))}
        />
        <LabelGroup
          title="Cash Flow Statement"
          fields={CF_ORDER}
          defaults={DEFAULT_CF_LABELS}
          values={cf}
          onChange={(k, v) => setCF((f) => ({ ...f, [k]: v }))}
          onReset={(k) => setCF((f) => ({ ...f, [k]: DEFAULT_CF_LABELS[k] }))}
        />

        <section className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 mb-1">Report Footer</h2>
          <p className="text-xs text-gray-500 mb-3">
            Optional text shown at the bottom of the P&amp;L, Balance Sheet, and Cash Flow reports.
            Useful for accountant disclaimers, preparation notes, or compilation language.
          </p>
          <textarea
            value={footer}
            onChange={(e) => setFooter(e.target.value.slice(0, REPORT_FOOTER_MAX_LENGTH))}
            rows={4}
            maxLength={REPORT_FOOTER_MAX_LENGTH}
            placeholder="e.g. See accompanying notes. Prepared without audit."
            className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
          />
          <div className="flex justify-between mt-1">
            <span className="text-xs text-gray-400">Line breaks are preserved.</span>
            <span className="text-xs text-gray-400">{footer.length}/{REPORT_FOOTER_MAX_LENGTH}</span>
          </div>
        </section>

        <section className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm space-y-4">
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-1">CPA Firm Identity</h2>
            <p className="text-xs text-gray-500">
              Used in the signature block of SSARS&nbsp;21 engagement letters (Admin&nbsp;→&nbsp;CPA&nbsp;Letters).
              Leave blank to fall back to your company name, city, and state.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Firm name</label>
              <Input value={firm.firmName} maxLength={200}
                onChange={(e) => setFirm((f) => ({ ...f, firmName: e.target.value }))}
                placeholder="e.g. Smith &amp; Co., CPAs" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Signature line</label>
              <Input value={firm.accountantSignature} maxLength={200}
                onChange={(e) => setFirm((f) => ({ ...f, accountantSignature: e.target.value }))}
                placeholder="Defaults to the firm name" />
              <p className="text-xs text-gray-500 mt-1">The name that signs the letter ({'{{accountant_signature}}'}).</p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">City</label>
              <Input value={firm.firmCity} maxLength={100}
                onChange={(e) => setFirm((f) => ({ ...f, firmCity: e.target.value }))}
                placeholder="e.g. Springfield" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">State</label>
              <Input value={firm.firmState} maxLength={100}
                onChange={(e) => setFirm((f) => ({ ...f, firmState: e.target.value }))}
                placeholder="e.g. MO" />
            </div>
          </div>
        </section>

        <div className="flex items-center gap-3 pt-2">
          <Button type="submit" disabled={saveStatus === 'saving'}>
            {saveStatus === 'saving' ? <><Loader2 className="h-4 w-4 mr-1 animate-spin" />Saving…</> : 'Save'}
          </Button>
          <Button type="button" variant="secondary" onClick={resetAll} disabled={saveStatus === 'saving'}>
            Reset all to defaults
          </Button>
          {saveStatus === 'saved' && (
            <span className="text-sm text-green-700 inline-flex items-center gap-1">
              <CheckCircle className="h-4 w-4" /> Saved
            </span>
          )}
          {saveStatus === 'error' && (
            <span className="text-sm text-red-600">{saveError}</span>
          )}
        </div>
      </form>
    </div>
  );
}

interface LabelGroupProps<K extends string> {
  title: string;
  fields: ReadonlyArray<{ key: K; helper: string }>;
  defaults: Record<K, string>;
  values: Record<K, string>;
  onChange: (key: K, value: string) => void;
  onReset: (key: K) => void;
}

function LabelGroup<K extends string>({ title, fields, defaults, values, onChange, onReset }: LabelGroupProps<K>) {
  return (
    <section className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm space-y-4">
      <h2 className="text-lg font-semibold text-gray-900">{title}</h2>
      {fields.map(({ key, helper }) => {
        const defaultValue = defaults[key];
        const isCustom = values[key] !== defaultValue;
        return (
          <div key={key}>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-sm font-medium text-gray-700">{defaultValue}</label>
              {isCustom && (
                <button
                  type="button"
                  onClick={() => onReset(key)}
                  className="text-xs text-gray-500 hover:text-gray-700 inline-flex items-center gap-1"
                >
                  <RotateCcw className="h-3 w-3" /> Reset
                </button>
              )}
            </div>
            <Input
              value={values[key]}
              onChange={(e) => onChange(key, e.target.value)}
              maxLength={80}
              placeholder={defaultValue}
            />
            <p className="text-xs text-gray-500 mt-1">{helper}</p>
          </div>
        );
      })}
    </section>
  );
}
