// Copyright 2026 Kisaes LLC
// Licensed under the PolyForm Internal Use License 1.0.0.
// You may not distribute this software. See LICENSE for terms.

// Fallback CycloneDX SBOM generator that reads package-lock.json
// directly — no `npm ls`. cyclonedx-npm shells `npm ls --json --all`,
// which on some npm versions emits UNPARSEABLE output under ELSPROBLEMS
// (our intentional `invalid:` overrides for unzipper/esbuild), so it
// can produce no SBOM and blocks the release. This derives a valid,
// deterministic CycloneDX 1.5 document from the lockfile instead. The
// authoritative, image-attached SBOM is still generated by syft in the
// docker-publish workflow; this is the license-check records copy.
//
// Usage: SBOM_OUT=path/to/sbom.cdx.json node scripts/lockfile-sbom.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const out = process.env.SBOM_OUT;
if (!out) {
  console.error('SBOM_OUT env var is required');
  process.exit(1);
}

const lock = JSON.parse(readFileSync('package-lock.json', 'utf8'));
const NM = 'node_modules/';
const components = new Map();

for (const [path, info] of Object.entries(lock.packages || {})) {
  if (!path.startsWith(NM)) continue; // skip the root ("") entry
  const name = path.slice(path.lastIndexOf(NM) + NM.length);
  const version = info?.version;
  if (!name || !version) continue;
  const key = `${name}@${version}`;
  if (components.has(key)) continue;
  // purl: scoped packages keep the '/', but the leading '@' is encoded.
  const purlName = name.startsWith('@') ? `%40${name.slice(1)}` : name;
  components.set(key, {
    type: 'library',
    name,
    version,
    purl: `pkg:npm/${purlName}@${version}`,
    ...(info.license ? { licenses: [{ license: { id: String(info.license) } }] } : {}),
  });
}

const bom = {
  bomFormat: 'CycloneDX',
  specVersion: '1.5',
  version: 1,
  metadata: {
    tools: [{ vendor: 'Vibe MyBooks', name: 'lockfile-sbom-fallback' }],
  },
  components: [...components.values()],
};

writeFileSync(out, JSON.stringify(bom, null, 2));
console.log(`lockfile SBOM: ${components.size} components -> ${out}`);
