// Copyright 2026 Kisaes LLC
// Licensed under the PolyForm Internal Use License 1.0.0.
// You may not distribute this software. See LICENSE for terms.

/**
 * Standalone migrate entrypoint. Runs all pending Drizzle migrations
 * and exits — used by the appliance compose as a one-shot container
 * before the api container is started with MIGRATIONS_AUTO=false, and
 * by CI to migrate the test DB before running the unit-test suite.
 *
 * Invoke from any cwd:
 *
 *   npx tsx packages/api/src/migrate.ts
 *
 * or, from inside `packages/api/`:
 *
 *   npm run migrate
 *
 * Idempotent — drizzle skips migrations already recorded in
 * `drizzle.__drizzle_migrations`.
 *
 * NOTE: this script deliberately bypasses `config/env.ts` so it can run
 * with only `DATABASE_URL` present. Migrations do not need
 * `ENCRYPTION_KEY` / `JWT_SECRET` / `PLAID_ENCRYPTION_KEY`, and forcing
 * the operator to provide them just to run migrations would couple
 * schema management to secret generation in a way that breaks both CI
 * and the appliance's "secrets generated by installer, then migrate,
 * then start" flow.
 */

import { drizzle } from 'drizzle-orm/node-postgres';
import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import pg from 'pg';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const databaseUrl = process.env['DATABASE_URL'];
if (!databaseUrl) {
  console.error('[migrate] DATABASE_URL is required');
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_FOLDER = resolve(here, 'db', 'migrations');

interface MigrationsJournal {
  entries: Array<{ idx: number; tag: string; when: number }>;
}

function readJournal(): MigrationsJournal {
  const journalPath = resolve(MIGRATIONS_FOLDER, 'meta', '_journal.json');
  return JSON.parse(readFileSync(journalPath, 'utf8')) as MigrationsJournal;
}

async function appliedCount(db: ReturnType<typeof drizzle>): Promise<number> {
  try {
    const result = await db.execute(
      sql`SELECT count(*)::int AS n FROM "drizzle"."__drizzle_migrations"`,
    );
    const row = (result.rows[0] as { n?: number } | undefined) ?? {};
    return Number(row.n ?? 0);
  } catch {
    return 0;
  }
}

async function main(): Promise<void> {
  const pool = new pg.Pool({ connectionString: databaseUrl });
  const db = drizzle(pool);

  try {
    const total = readJournal().entries.length;
    const before = await appliedCount(db);
    console.log(
      `[migrate] migration status before run: ${before}/${total} applied (${
        before < total ? 'pending' : 'up to date'
      })`,
    );

    if (before < total) {
      await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
      const after = await appliedCount(db);
      console.log(`[migrate] migrations applied (${after}/${total}).`);
      if (after < total) {
        throw new Error(
          `migrate completed but ${total - after} migration(s) still pending — ` +
            `inspect drizzle.__drizzle_migrations to diagnose`,
        );
      }
    } else {
      console.log('[migrate] nothing to do.');
    }
  } finally {
    await pool.end().catch(() => {
      /* ignore */
    });
  }
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error('[migrate] migration run failed:', err);
    process.exit(1);
  },
);
