import { useState, useEffect, useMemo, useRef, type FormEvent, type DragEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useCreateBill, useUpdateBill } from '../../api/hooks/useAp';
import { apiClient } from '../../api/client';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { DatePicker } from '../../components/forms/DatePicker';
import { AccountSelector } from '../../components/forms/AccountSelector';
import { ContactSelector } from '../../components/forms/ContactSelector';
import { MoneyInput } from '../../components/forms/MoneyInput';
import { LoadingSpinner } from '../../components/ui/LoadingSpinner';
import { Plus, Trash2, Sparkles, FileText, X } from 'lucide-react';

interface BillLine {
  accountId: string;
  description: string;
  amount: string;
}

interface OcrExtraction {
  vendor: string | null;
  vendorInvoiceNumber: string | null;
  billDate: string | null;
  dueDate: string | null;
  paymentTerms: string | null;
  total: string | null;
  subtotal: string | null;
  tax: string | null;
  notes: string | null;
  confidence: number;
  contactId: string | null;
  defaultExpenseAccountId: string | null;
  lineItems: Array<{ description: string | null; amount: string | null; quantity: string | null }>;
}

interface UploadedAttachment {
  id: string;
  fileName: string;
  mimeType: string;
}

const VALID_TERMS = new Set(['due_on_receipt', 'net_10', 'net_15', 'net_30', 'net_45', 'net_60', 'net_90']);

const TERM_DAYS: Record<string, number> = {
  due_on_receipt: 0,
  net_10: 10,
  net_15: 15,
  net_30: 30,
  net_45: 45,
  net_60: 60,
  net_90: 90,
};

function emptyLine(): BillLine {
  return { accountId: '', description: '', amount: '' };
}

function calcDueDate(billDate: string, terms: string, customDays: string): string {
  if (!billDate) return '';
  const d = new Date(billDate);
  let days: number | undefined;
  if (terms === 'custom') {
    days = parseInt(customDays || '0', 10);
  } else if (terms in TERM_DAYS) {
    days = TERM_DAYS[terms];
  }
  if (days === undefined || isNaN(days)) return '';
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0]!;
}

export function EnterBillPage() {
  const navigate = useNavigate();
  const { id: editId } = useParams<{ id: string }>();
  const isEdit = !!editId;
  const today = new Date().toISOString().split('T')[0]!;

  const createBill = useCreateBill();
  const updateBill = useUpdateBill();

  const [contactId, setContactId] = useState('');
  const [txnDate, setTxnDate] = useState(today);
  const [dueDate, setDueDate] = useState('');
  const [paymentTerms, setPaymentTerms] = useState('net_30');
  const [customDays, setCustomDays] = useState('');
  const [vendorInvoiceNumber, setVendorInvoiceNumber] = useState('');
  const [memo, setMemo] = useState('');
  const [internalNotes, setInternalNotes] = useState('');
  const [dueDateManual, setDueDateManual] = useState(false);
  const [lines, setLines] = useState<BillLine[]>([emptyLine()]);
  const [loaded, setLoaded] = useState(!isEdit);
  const [andNew, setAndNew] = useState(false);

  // ─── OCR / Attachment state ───────────────────────────────────
  // A stable draft id for this bill-entry session. Any uploaded attachments
  // are saved with attachable_type='draft' + attachable_id=draftId so we can
  // re-link them to the real bill after it's saved (via /bills/:id/attach-draft).
  // The id is regenerated by resetForNew() so "Save + New" starts fresh.
  const [draftId, setDraftId] = useState(() => crypto.randomUUID());
  const [uploads, setUploads] = useState<UploadedAttachment[]>([]);
  const [ocrPending, setOcrPending] = useState(false);
  const [ocrError, setOcrError] = useState<string | null>(null);
  const [ocrExtraction, setOcrExtraction] = useState<OcrExtraction | null>(null);
  const [ocrDragging, setOcrDragging] = useState(false);
  const ocrFileInputRef = useRef<HTMLInputElement>(null);

  // Edit-mode load
  const { data: existingData } = useQuery({
    queryKey: ['bills', editId],
    queryFn: () => apiClient<{ bill: any }>(`/bills/${editId}`),
    enabled: isEdit,
  });

  useEffect(() => {
    if (!existingData?.bill) return;
    const b = existingData.bill;
    setContactId(b.contactId || '');
    setTxnDate(b.txnDate || today);
    setDueDate(b.dueDate || '');
    setPaymentTerms(b.paymentTerms || 'net_30');
    setCustomDays(b.termsDays ? String(b.termsDays) : '');
    setVendorInvoiceNumber(b.vendorInvoiceNumber || '');
    setMemo(b.memo || '');
    setInternalNotes(b.internalNotes || '');
    setDueDateManual(true);

    const billLines: BillLine[] = (b.lines || [])
      .filter((l: any) => parseFloat(l.debit) > 0 && l.accountId)
      .map((l: any) => ({
        accountId: l.accountId,
        description: l.description || '',
        amount: parseFloat(l.debit).toFixed(2),
      }));
    if (billLines.length > 0) setLines(billLines);
    setLoaded(true);
  }, [existingData, today]);

  // Auto-recalc due date when terms or txn date change (unless user manually edited)
  useEffect(() => {
    if (!isEdit && !dueDateManual && txnDate) {
      setDueDate(calcDueDate(txnDate, paymentTerms, customDays));
    }
  }, [txnDate, paymentTerms, customDays, isEdit, dueDateManual]);

  // ─── OCR upload + extract pipeline ────────────────────────────
  //
  // Flow:
  //   1. Upload file → POST /api/v1/attachments (multipart) with
  //      attachable_type='draft', attachable_id=draftId. Returns an attachment id.
  //   2. Run extraction → POST /api/v1/bills/extract-from-attachment/:id.
  //      Returns parsed vendor/dates/lines plus a resolved contactId if the
  //      vendor name matched a tenant contact.
  //   3. Apply extraction → fill any blank form fields. We don't overwrite
  //      fields the user has already typed in.
  //
  // The extraction is idempotent: re-running it on the same file returns the
  // same fields, and the user can clear-and-redo if needed.
  const handleOcrFile = async (file: File) => {
    setOcrError(null);
    setOcrPending(true);
    try {
      // 1. Upload as a draft attachment
      const formData = new FormData();
      formData.append('file', file);
      formData.append('attachableType', 'draft');
      formData.append('attachableId', draftId);
      const uploadRes = await fetch('/api/v1/attachments', {
        method: 'POST',
        headers: { Authorization: `Bearer ${localStorage.getItem('accessToken') || ''}` },
        body: formData,
      });
      if (!uploadRes.ok) {
        const err = await uploadRes.json().catch(() => ({}));
        throw new Error(err?.error?.message || 'File upload failed');
      }
      const uploadData = await uploadRes.json();
      const attachmentId: string = uploadData.attachment.id;
      setUploads((prev) => [...prev, {
        id: attachmentId,
        fileName: uploadData.attachment.fileName,
        mimeType: uploadData.attachment.mimeType,
      }]);

      // 2. Run bill OCR
      const extractRes = await apiClient<{ extraction: OcrExtraction }>(
        `/bills/extract-from-attachment/${attachmentId}`,
        { method: 'POST' },
      );
      const ext = extractRes.extraction;
      setOcrExtraction(ext);

      // 3. Pre-fill the form. Only fill fields the user hasn't already
      // touched, so re-running OCR or uploading a second file doesn't wipe
      // manual edits.
      applyExtraction(ext);
    } catch (err: any) {
      setOcrError(err?.message || 'Failed to extract bill data');
    } finally {
      setOcrPending(false);
    }
  };

  /**
   * Apply OCR results to form state. Only writes to fields that are still
   * empty (or default for date fields), so we never clobber user input.
   */
  const applyExtraction = (ext: OcrExtraction) => {
    if (ext.contactId && !contactId) setContactId(ext.contactId);
    if (ext.billDate) {
      setTxnDate(ext.billDate);
    }
    if (ext.vendorInvoiceNumber && !vendorInvoiceNumber) setVendorInvoiceNumber(ext.vendorInvoiceNumber);
    if (ext.notes && !memo) setMemo(ext.notes);

    // Payment terms: only set if model returned one of our known codes.
    // If it gave us a non-standard string we leave the existing value alone
    // so the dropdown stays valid.
    if (ext.paymentTerms && VALID_TERMS.has(ext.paymentTerms)) {
      setPaymentTerms(ext.paymentTerms);
      setDueDateManual(false); // let the auto-recalc fire from new bill date + terms
    }

    // Due date: prefer model's explicit due date over the calc; mark as
    // manual so the terms-based recalc doesn't immediately overwrite it.
    if (ext.dueDate) {
      setDueDate(ext.dueDate);
      setDueDateManual(true);
    }

    // Line items: replace the empty initial line with the extracted ones.
    // Use vendor's defaultExpenseAccountId for any line that doesn't get a
    // model-suggested account (which is none — the model returns descriptions
    // and amounts, not GL accounts).
    if (ext.lineItems && ext.lineItems.length > 0) {
      const formLines: BillLine[] = ext.lineItems
        .filter((li) => li.amount && parseFloat(li.amount) > 0)
        .map((li) => ({
          accountId: ext.defaultExpenseAccountId || '',
          description: li.description || '',
          amount: parseFloat(li.amount!).toFixed(2),
        }));
      if (formLines.length > 0) {
        // Only replace if the form is still showing the initial empty line.
        // If the user already typed something, append instead.
        const hasUserContent = lines.some((l) => l.accountId || l.description || l.amount);
        setLines(hasUserContent ? [...lines, ...formLines] : formLines);
      }
    } else if (ext.total && parseFloat(ext.total) > 0) {
      // Fall back: no line items but a total — create one summary line.
      const formLines: BillLine[] = [{
        accountId: ext.defaultExpenseAccountId || '',
        description: ext.notes || 'Vendor invoice',
        amount: parseFloat(ext.total).toFixed(2),
      }];
      const hasUserContent = lines.some((l) => l.accountId || l.description || l.amount);
      if (!hasUserContent) setLines(formLines);
    }
  };

  const handleOcrDrop = (e: DragEvent) => {
    e.preventDefault();
    setOcrDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) handleOcrFile(file);
  };

  const removeUpload = async (attachmentId: string) => {
    try {
      await apiClient(`/attachments/${attachmentId}`, { method: 'DELETE' });
    } catch {
      // best-effort — even if delete fails on the server, drop it from the list
    }
    setUploads((prev) => prev.filter((u) => u.id !== attachmentId));
  };

  const ocrConfidenceBadge = useMemo(() => {
    if (!ocrExtraction) return null;
    const c = ocrExtraction.confidence;
    if (c >= 0.85) return { label: 'High', cls: 'bg-green-100 text-green-700' };
    if (c >= 0.6) return { label: 'Medium', cls: 'bg-yellow-100 text-yellow-700' };
    return { label: 'Low — please review', cls: 'bg-red-100 text-red-700' };
  }, [ocrExtraction]);

  const updateLine = (i: number, field: keyof BillLine, value: string) =>
    setLines((prev) => prev.map((l, idx) => (idx === i ? { ...l, [field]: value } : l)));

  const total = lines.reduce((s, l) => s + (parseFloat(l.amount) || 0), 0);

  const buildPayload = () => ({
    contactId,
    txnDate,
    dueDate: dueDate || undefined,
    paymentTerms,
    termsDays: paymentTerms === 'custom' && customDays ? parseInt(customDays, 10) : undefined,
    vendorInvoiceNumber: vendorInvoiceNumber || undefined,
    memo: memo || undefined,
    internalNotes: internalNotes || undefined,
    lines: lines
      .filter((l) => l.accountId && l.amount && parseFloat(l.amount) > 0)
      .map((l) => ({
        accountId: l.accountId,
        description: l.description || undefined,
        amount: l.amount,
      })),
  });

  const resetForNew = () => {
    setContactId('');
    setVendorInvoiceNumber('');
    setMemo('');
    setInternalNotes('');
    setLines([emptyLine()]);
    setDueDateManual(false);
    setAndNew(false);
    // Fresh OCR state for the next bill
    setDraftId(crypto.randomUUID());
    setUploads([]);
    setOcrExtraction(null);
    setOcrError(null);
  };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    const payload = buildPayload();
    if (payload.lines.length === 0) return;

    if (isEdit) {
      updateBill.mutate({ id: editId!, input: payload }, {
        onSuccess: () => navigate(`/bills/${editId}`),
      });
    } else {
      createBill.mutate(payload, {
        onSuccess: async (data) => {
          // If the user uploaded any vendor invoice files during OCR, relink
          // the draft attachments to the newly created bill so they show up
          // on the bill detail page and in the attachment library.
          if (uploads.length > 0) {
            try {
              await apiClient(`/bills/${data.bill.id}/attach-draft`, {
                method: 'POST',
                body: JSON.stringify({ draftId }),
              });
            } catch {
              // best-effort — the bill is already created; the user can
              // manually attach files from the bill detail page if this fails
            }
          }
          if (andNew) resetForNew();
          else navigate(`/bills/${data.bill.id}`);
        },
      });
    }
  };

  const error = isEdit ? updateBill.error : createBill.error;
  const isPending = isEdit ? updateBill.isPending : createBill.isPending;

  if (!loaded) return <LoadingSpinner className="py-12" />;

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">{isEdit ? 'Edit Bill' : 'Enter Bill'}</h1>

      {/* OCR upload zone — only on new bills, not on edit */}
      {!isEdit && (
        <div className="max-w-5xl mb-6">
          <div
            onDragOver={(e) => { e.preventDefault(); setOcrDragging(true); }}
            onDragLeave={() => setOcrDragging(false)}
            onDrop={handleOcrDrop}
            onClick={() => ocrFileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors cursor-pointer ${
              ocrDragging ? 'border-primary-400 bg-primary-50' : 'border-gray-300 hover:border-gray-400 bg-white'
            }`}
          >
            <input
              ref={ocrFileInputRef}
              type="file"
              accept="image/*,application/pdf"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) handleOcrFile(file);
                e.target.value = '';
              }}
            />
            {ocrPending ? (
              <div className="flex items-center justify-center gap-3 py-2">
                <LoadingSpinner />
                <span className="text-sm text-gray-600">Reading vendor invoice with AI...</span>
              </div>
            ) : (
              <>
                <Sparkles className="h-8 w-8 text-primary-500 mx-auto mb-2" />
                <p className="text-sm font-medium text-gray-700">
                  Drop a vendor invoice (PDF or image) to auto-fill this form
                </p>
                <p className="text-xs text-gray-500 mt-1">
                  AI extracts vendor, dates, invoice number, and line items. You review and save.
                </p>
              </>
            )}
          </div>

          {ocrError && (
            <div className="mt-2 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
              {ocrError}
            </div>
          )}

          {ocrExtraction && ocrConfidenceBadge && (
            <div className="mt-2 p-3 bg-primary-50 border border-primary-200 rounded-lg text-sm flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-primary-600" />
                <span className="text-gray-700">
                  Pre-filled from vendor invoice
                  {ocrExtraction.contactId && ' — vendor matched'}
                  {!ocrExtraction.contactId && ocrExtraction.vendor && ` — vendor "${ocrExtraction.vendor}" not in your contacts (please pick or create)`}
                </span>
              </div>
              <span className={`px-2 py-0.5 rounded text-xs font-medium ${ocrConfidenceBadge.cls}`}>
                {ocrConfidenceBadge.label}
              </span>
            </div>
          )}

          {uploads.length > 0 && (
            <div className="mt-2 space-y-1">
              {uploads.map((u) => (
                <div key={u.id} className="flex items-center justify-between p-2 bg-gray-50 border border-gray-200 rounded text-sm">
                  <div className="flex items-center gap-2 text-gray-700">
                    <FileText className="h-4 w-4 text-gray-500" />
                    <span className="truncate max-w-md">{u.fileName}</span>
                  </div>
                  <button
                    type="button"
                    onClick={() => removeUpload(u.id)}
                    className="text-gray-400 hover:text-red-500"
                    title="Remove"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              ))}
              <p className="text-xs text-gray-500">
                Will be attached to the bill on save.
              </p>
            </div>
          )}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6 max-w-5xl">
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6 space-y-4">
          <ContactSelector
            label="Vendor"
            value={contactId}
            onChange={setContactId}
            contactTypeFilter="vendor"
            required
          />
          <div className="grid grid-cols-3 gap-4">
            <DatePicker label="Bill Date" value={txnDate} onChange={(e) => setTxnDate(e.target.value)} required />
            <DatePicker
              label="Due Date"
              value={dueDate}
              onChange={(e) => { setDueDate(e.target.value); setDueDateManual(true); }}
            />
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Payment Terms</label>
              <select
                value={paymentTerms}
                onChange={(e) => { setPaymentTerms(e.target.value); setDueDateManual(false); }}
                className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
              >
                <option value="due_on_receipt">Due On Receipt</option>
                <option value="net_10">Net 10</option>
                <option value="net_15">Net 15</option>
                <option value="net_30">Net 30</option>
                <option value="net_45">Net 45</option>
                <option value="net_60">Net 60</option>
                <option value="net_90">Net 90</option>
                <option value="custom">Custom</option>
              </select>
            </div>
          </div>
          {paymentTerms === 'custom' && (
            <div className="grid grid-cols-3 gap-4">
              <Input
                label="Custom Days"
                type="number"
                min="0"
                value={customDays}
                onChange={(e) => { setCustomDays(e.target.value); setDueDateManual(false); }}
              />
            </div>
          )}
          <Input
            label="Vendor Invoice #"
            value={vendorInvoiceNumber}
            onChange={(e) => setVendorInvoiceNumber(e.target.value)}
            placeholder="The vendor's reference number"
          />
        </div>

        <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
          <h2 className="text-sm font-medium text-gray-700 mb-3">Expense Lines</h2>
          <table className="min-w-full">
            <thead>
              <tr>
                <th className="text-left text-xs font-medium text-gray-500 uppercase pb-2 w-1/3">Account</th>
                <th className="text-left text-xs font-medium text-gray-500 uppercase pb-2">Description</th>
                <th className="text-right text-xs font-medium text-gray-500 uppercase pb-2 w-32">Amount</th>
                <th className="w-8 pb-2" />
              </tr>
            </thead>
            <tbody>
              {lines.map((line, i) => (
                <tr key={i} className="align-top">
                  <td className="pr-2 py-1">
                    <AccountSelector
                      value={line.accountId}
                      onChange={(v) => updateLine(i, 'accountId', v)}
                      accountTypeFilter={['expense', 'asset'] as any}
                    />
                  </td>
                  <td className="px-2 py-1">
                    <input
                      value={line.description}
                      onChange={(e) => updateLine(i, 'description', e.target.value)}
                      className="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                      placeholder="Description"
                    />
                  </td>
                  <td className="px-2 py-1">
                    <MoneyInput value={line.amount} onChange={(v) => updateLine(i, 'amount', v)} />
                  </td>
                  <td className="pl-1 py-1 pt-2.5">
                    {lines.length > 1 && (
                      <button
                        type="button"
                        onClick={() => setLines((p) => p.filter((_, idx) => idx !== i))}
                        className="text-gray-400 hover:text-red-500"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <button
            type="button"
            onClick={() => setLines((p) => [...p, emptyLine()])}
            className="mt-3 flex items-center gap-1 text-sm text-primary-600"
          >
            <Plus className="h-4 w-4" /> Add line
          </button>

          <div className="flex justify-end mt-4 border-t pt-4">
            <div className="w-64 space-y-1 text-sm">
              <div className="flex justify-between font-bold text-lg">
                <span>Total</span>
                <span className="font-mono">${total.toFixed(2)}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6 space-y-4">
          <Input label="Memo" value={memo} onChange={(e) => setMemo(e.target.value)} />
          <Input label="Internal Notes" value={internalNotes} onChange={(e) => setInternalNotes(e.target.value)} />
        </div>

        {error && <p className="text-sm text-red-600">{error.message}</p>}

        <div className="flex gap-3">
          <Button type="submit" loading={isPending && !andNew}>
            {isEdit ? 'Save Changes' : 'Create Bill'}
          </Button>
          {!isEdit && (
            <Button
              type="button"
              variant="secondary"
              loading={isPending && andNew}
              onClick={() => { setAndNew(true); document.querySelector<HTMLFormElement>('form')?.requestSubmit(); }}
            >
              Save + New
            </Button>
          )}
          <Button
            type="button"
            variant="secondary"
            onClick={() => navigate(isEdit ? `/bills/${editId}` : '/bills')}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
