# Vibe MyBooks — Windows Setup Script
# This script is called by the Inno Setup installer to configure the environment.

param(
    [string]$InstallDir,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

function Write-Status($msg) {
    Write-Host "[Vibe MyBooks] $msg" -ForegroundColor Cyan
}

function Write-Err($msg) {
    Write-Host "[Vibe MyBooks ERROR] $msg" -ForegroundColor Red
}

# ─── Uninstall ──────────────────────────────────────────────────
if ($Uninstall) {
    Write-Status "Stopping Vibe MyBooks containers..."
    try {
        Set-Location $InstallDir
        & docker compose -f docker-compose.prod.yml down 2>$null
    } catch {}
    Write-Status "Removing Docker volumes (database + queue)..."
    try {
        & docker volume rm mybooks_pgdata mybooks_redis-data 2>$null
    } catch {}
    # Note: attachments and backups live in "$InstallDir\data" on the host.
    # We intentionally do NOT delete them here — users may want to preserve
    # their bookkeeping data (receipts, PDFs, backups) after uninstalling the
    # application. Manual cleanup:
    #   Remove-Item -Recurse -Force "$InstallDir\data"
    if (Test-Path (Join-Path $InstallDir "data")) {
        Write-Status "Your bookkeeping data is preserved at: $InstallDir\data"
        Write-Status "Delete it manually if you no longer need it."
    }
    Write-Status "Uninstall complete."
    exit 0
}

# ─── Check Docker Desktop ──────────────────────────────────────
Write-Status "Checking for Docker Desktop..."

$dockerPath = "$env:ProgramFiles\Docker\Docker\Docker Desktop.exe"
$dockerInstalled = Test-Path $dockerPath

if (-not $dockerInstalled) {
    Write-Status "Docker Desktop not found. Downloading installer..."

    $dockerInstallerUrl = "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
    $dockerInstallerPath = "$env:TEMP\DockerDesktopInstaller.exe"

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $webClient = New-Object System.Net.WebClient
        $webClient.DownloadFile($dockerInstallerUrl, $dockerInstallerPath)

        Write-Status "Installing Docker Desktop (this may take several minutes)..."
        Start-Process -FilePath $dockerInstallerPath -ArgumentList "install", "--quiet", "--accept-license" -Wait -NoNewWindow

        Write-Status "Docker Desktop installed. A restart may be required."
    } catch {
        Write-Err "Failed to install Docker Desktop: $_"
        Write-Err "Please install Docker Desktop manually from https://docker.com/products/docker-desktop"
        Read-Host "Press Enter to continue after installing Docker Desktop"
    }
}

# ─── Ensure Docker is running ───────────────────────────────────
Write-Status "Starting Docker Desktop..."

$dockerRunning = $false
try {
    $null = & docker info 2>$null
    $dockerRunning = ($LASTEXITCODE -eq 0)
} catch {}

if (-not $dockerRunning) {
    # Start Docker Desktop
    if (Test-Path $dockerPath) {
        Start-Process $dockerPath
        Write-Status "Waiting for Docker to start (this may take 30-60 seconds)..."

        $maxWait = 120  # seconds
        $waited = 0
        while ($waited -lt $maxWait) {
            Start-Sleep -Seconds 5
            $waited += 5
            try {
                $null = & docker info 2>$null
                if ($LASTEXITCODE -eq 0) {
                    $dockerRunning = $true
                    break
                }
            } catch {}
            Write-Host "  Waiting... ($waited seconds)" -ForegroundColor Gray
        }
    }

    if (-not $dockerRunning) {
        Write-Err "Docker Desktop did not start within 2 minutes."
        Write-Err "Please start Docker Desktop manually, then run this setup again."
        exit 1
    }
}

Write-Status "Docker is running."

# ─── Generate .env file ────────────────────────────────────────
Write-Status "Generating configuration..."

$envFile = Join-Path $InstallDir ".env"

if (-not (Test-Path $envFile)) {
    # Generate secure random secrets
    $jwtSecret = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 40 | ForEach-Object { [char]$_ })
    $encryptionKey = -join ((48..57) + (97..102) | Get-Random -Count 64 | ForEach-Object { [char]$_ })

    $envContent = @"
# Vibe MyBooks Configuration (auto-generated by installer)
DATABASE_URL=postgresql://kisbooks:kisbooks@db:5432/kisbooks
REDIS_URL=redis://redis:6379
JWT_SECRET=$jwtSecret
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
PORT=3001
VITE_PORT=5173
DB_HOST_PORT=5434
REDIS_HOST_PORT=6379
NODE_ENV=production
CORS_ORIGIN=http://localhost:3001
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@example.com
UPLOAD_DIR=/data/uploads
MAX_FILE_SIZE_MB=10
PLAID_CLIENT_ID=
PLAID_SECRET=
PLAID_ENV=sandbox
PLAID_ENCRYPTION_KEY=$encryptionKey
ANTHROPIC_API_KEY=
LLM_MODEL=claude-sonnet-4-20250514
BACKUP_DIR=/data/backups
BACKUP_ENCRYPTION_KEY=
"@
    Set-Content -Path $envFile -Value $envContent
    Write-Status "Configuration file created."
} else {
    Write-Status "Configuration file already exists, keeping it."
}

# ─── Build and start containers ─────────────────────────────────
Write-Status "Building and starting Vibe MyBooks (first run may take 5-10 minutes)..."

Set-Location $InstallDir
& docker compose -f docker-compose.prod.yml up -d --build 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Err "Failed to start containers. Check Docker Desktop logs."
    exit 1
}

# ─── Wait for health check ─────────────────────────────────────
Write-Status "Waiting for Vibe MyBooks to be ready..."

$maxWait = 120
$waited = 0
$ready = $false

while ($waited -lt $maxWait) {
    Start-Sleep -Seconds 3
    $waited += 3
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:3001/health" -TimeoutSec 5 -UseBasicParsing -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            $ready = $true
            break
        }
    } catch {}
    Write-Host "  Starting... ($waited seconds)" -ForegroundColor Gray
}

if ($ready) {
    Write-Status "Vibe MyBooks is ready!"
    Write-Status "Opening browser..."
    Start-Process "http://localhost:3001"
} else {
    Write-Err "Vibe MyBooks did not become ready within 2 minutes."
    Write-Err "Try opening http://localhost:3001 in your browser manually."
}

Write-Status "Setup complete!"
